// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9aXMbN7J/BTX7qjZ5y1OWnKyqXPUkOnaUtWyVKHs/rF0OONPkIJoBJgCGMpPSf3+F",
	"Y27McCRRPrL8YlME0Gj0hUZ3A/zT81mcMApUCu/4T0/4IcRYfzxZAZXqQ8JZAlwS0F/7HLCE4EQ3LRmP",
	"sfSOvQBLGEoSgzfw5CYB79gTkhO68m4HakgAVBIcveWRGtboQYIKtDQlgQuQkFimGgugaewd/8ejTA59",
	"Rin4EtSQG0wkoavhkvFhMa3wBh5wzrg38FZYhqAADgklqnFI6BqoZHzjDbw0GUo2VKvxBp5gKfdhuGIU",
	"vA+t6JzRJXMuKk2Cu1JqDVwQRh3gbgceh99TwiFQ69b0seSoIFKn9qDEsDJKxVzFytjiN/ClwkPz/oKz",
	"T5umAIRSJpaPMaGvgK5k6B1PBx5NowgvIvCOJU+hvrqB92nIcEKGPgtgBXQInyTHQ4lXGuoaR0ST/dhj",
	"MZGURIOURwMhMZeCMnlDZPhMTS00LfSnz4xFDQXKcgI9LgYx/vRsOplMvFs1bZNXQoAQ8a6UtacqUhyD",
	"U+rZDQX+gnAhX9suAQifk0RqwfbeqPa/C7RUXZAGM2iB8gpvAxLhDhiC4kSEzBg2IiHWH/6Hw9I79v42",
	"Lgzf2Fq98dyO8Ao6Y87xRkPTxuCsp6HSna/014WxKhsavpaMacNk+joMjEvl7VpL8KsKXqz5Q6eovGA8",
	"bopLgeAWQp3lHVtFob+cZ4sc4By9jxrm7cPIXhWZuW5DbIlkCKiYCgVY4uP3FP0v+jVf/69oiM4xTXGE",
	"8u9QmkQMB2hNMPpl/ua1GYKVpVTdZyyK9C6EFhsUkxXHamKURJhS4Ej3e0+9wcPJxCiw5bMCLw3aGIey",
	"vDRFpVskXhEhe2tKyeg4dKVovTRi7ha3JYkcjHpBIshovWS8zipvUMjBglCstemhNDUG3WlqlAFqSs0u",
	"+NgUdzcHNZm6efc2McDryJvvFRnj5hpG3qDGkK+CAo1lzqJUSOCXZpTqLdRnMOJaxdU2oARvcgHyceSn",
	"EVZ+IfINLMRLwBpksJ2M0anCP3ueUSKDJFk+AVTAqrl3JZo+o5Kz6CLCFOZ+CEFqPQyF3xKnkfSOlzgS",
	"MKjhexJF7AbdMH6tySHMWEUJRpGFqm0UIMoCEAXCC8YiwFT770n6Zg18xuKYyEtl1yoTe9PjQ68+8ezi",
	"LWJr4ENfj0LaHKLvYLQaDdB7NeS9971yy+3eOD2eegNvenyg/z3U/z5tboqKfmrIcI25Ehmhxs6S9A2F",
	"K/aGKnXJ/rq6YaW/XrCUl/6ck08K+L2YEUPM+GYLRQ4aFDnXw7qJctBNlH7kMBOVKFL6whCl9IWmy30p",
	"oeQK+GsWwOzibVNZlAz4jINACXBkOmsxK6SMUAkr4PcxHjGhzw60c3ygfeMyOmaBTYwsD757efr9o+F0",
	"qHE6mh7UcLoKOeBAOOxrGi+AK7uiCCZNtzp66DtlyubnV4U5Y/T7ETpbIsokSjhbkwCCgbLQaQwCUaZ7",
	"f5fBe2ZY8f0InadCogWg9+lk8gSeoSoXH0AGdWCBOJEbw5vmhlYYVqdRaVOtuqA5OP2h774hEkaFY5Ob",
	"OTaGMqkRB5FG7ZvFnPyhFHKL2zSrdFanrcyLu2ISR6K33227a/oaD2/GqEhju5wtxxw9/aVjYAvDLL7u",
	"yZqL6GBGQabagW4NHEdRvqsK3Q+JNI6Nh1cjemk/fK33rQ6t6tzmMim/HXhLTCJlnbcCzDoaWAgHAVhX",
	"dY1JhBckInLjnEIqAjltpSYdKiwm9jkTAimatGOswbXZOgMxLlm8/jBbSGBA0pwQZv3fWTP1jyqlv3eC",
	"LzS3k8Qly+dCsyamJZyrMwwcklJndIkrVYq6xPg5llhIxqF5mgmIuDYuY+NcuuQAM5xgn8jNy9NSlxJh",
	"QsyDG8zhxPchAq5O9OdsXT5YlzyykAnpdE915G9JDBGVm6p6opsQOCAZEqGPUHoBiAiEpcTKI/S2Ba2U",
	"18MCcAdvE84k81mUnbsbHQx9t6xfto1eAw0Y3x4SlSYaUp+sQf0c4iBjWTvxa4vLqOCSjJ90fLkhFTEI",
	"gVeODUf3R1mzg+DcHGXcbM7YazuhFVCFtrKZ6uss2N1NsWzyDwp9IUmsd7rnIDGJmpOa7yFAkHe1myJa",
	"chYjjAShqwjyXVNjUNOR1IRFHOQwQCFAWR9tUbXM5luYdoJiLFU3LIqeZn3ac/6E40RJsfckPJzEE+Gm",
	"LBZOHD4pw2VAsiUK2Y0hZrHeG1w4BVptivmmk8lkNJmgl6cISzSdTlBMaCqt83s0mWjR62ZITp4cR5ek",
	"/UyEZCuOY7OChIOvsbGaW6M4lrgS1WnTvCJ6ExP6DkcpuHsLCYmrpS5bGRA7YmAwca6HCVfoOklnaifc",
	"5i/r7bLdgJUw95N0zvxrkFthCtutD1Ti0M+3lPyeAiKFNc5lWdljl0yaffr8tAlMkSfbxglF56flCBih",
	"8ulhLzzb7XdfA5ubzXYjmOXCaqeuRjSUULMCI+tVxq+INM5/E9BLIpE9OodYhBX984/w9OnT6eHTI3xw",
	"tJj+4APA4ocfgin4h5MAFkc/BD8G+PCwI+3mzjW8M406zTBACywgQIyiFZFI4lUFh8loOjocHk6GK4vN",
	"Vo0vFlvFooW4HDsUxbjM4gK48k58oBL4HVW+chjLUknNw7zq4+d9kD6djdAsN4jKKOv9F51EEdNWCa1n",
	"F28FGiPjO16EG0F85elatS2SUixV8pvjZrxMhVzusvRP5BRummOxSgUv2A3wucTSAMVBQNQ6cXRRoW0r",
	"5QquKGj9EdO2rgUnxUF7THJb9rvY8NpB2s3Ty5PzzLLch7V2aMZb+6c9BGle9uAuBak89v4kfG0GuFZt",
	"fD+rD24athx4Cs1pI7Dq9XPG62b7Ot4d+1ynGzN1U3hLBKxoituAlNJ7biPSpQy9AhOKkFppqzsATvRJ",
	"3J7udagSSabcK8JLKTab4Glgvi6s2p2wsOM+ks5Q/npmoG8z1iVog4JinZR+bt2vep7VWvLuxahO/Rf/",
	"zq7CCOPW3ueiub5Y6GiOmrdzVUWwqkbSnJFaZoV1e/JkSWOvv1c85N25UI5QFe4ugyN3mUDRcWucpBdA",
	"l9Yr6HeKT5wl68MZo0uycgQoTHriJZZwgzeVhDpJ1oe7SOiR5PAjDgJualaO9KICKj7bXCQ5CQIO4vPN",
	"KNIFBXmOxfVOSiAMuI8xFtcmtdEMohdrrMw+qPPXUN4lJL+wRVNmT7F/veIspQH6jS1s5n1D/XL+XVea",
	"uHz2oo8rXFHkqdHZc3QTAtVTKKsUgXIkROr7IMQyjaJN2Wtoq/OALNbSEVJBZGkWooMW7ZVOVRC/sAU6",
	"e+46YblOwlk1Ypeh/YUt5qZjVw1fC5vm+RRNNM1IW7mSAA0IXf2Khki1EYF+TyGFwLZiLmzrhfmILt9d",
	"MRYJ9NMnHyK0JBGYrlYobe/LlFLV+83FCXp3jrJGRoXpnbNQdT6pCUqNsWaEYUeGp/kL3RAZmpiVBYup",
	"D1Gpn4m72C91FU2WIrULVxJpVqYOUvkadADYomgDv/pDDstZ1/kKL8xRuSrk17DZiY5HGryShnUtzPJw",
	"mDURUyhn07hELD+ZF+G/e5dWFDVPksTlqNkO6yuKOUpBOVNnUZzCAxZjQof+j7upvmjNYfYmaFvO8byN",
	"Yq3JxgUHfB2wG3pfP70R5m246qfZFIoRJZQWm2pgt7F0c45qDfAanwjyMG/ByjyM2xndHaCsTOIgfDKJ",
	"baFEzvRD9aUr3Otyq54XcdaCop3sPBMideR8cKX2tln4ztJKSyNs2BgRZaanexWm28CrlGOZ2bYvo/9R",
	"u7Z8x4k7O4w3nc21uCHSD52rbC0elrWKWSExDTAPTK5GcrJIjSXPwQ+8lIo0SRiXLdZ8HWHakpdbx2LW",
	"xiJ3dom2BedMYttZFFTPc1eqfxwFBUnqjr41Kof6BVji7lqYe0Gt28QkzYs3Oqhz6S5VqG8zphPyi17Z",
	"4azrKOkkW3GKtIky4wZsJ1pEYiLF3QopXpkxHSRvnjrviBZrytd2/OpC+UDuvcpJ08I4S7s7Migf9QCR",
	"btK3P9Q7EyW7K7CTSxf3KLyvnyZKlwsKDJyYmwsHzc0su/DVWfi9sjXfj3e1hLjzHEl222YreuZejjqh",
	"ifAiXUTE/xdsHfnOOn/BfP5zMUhvEqVNrhNC3tFZxny/yxV6p++/Y5uji2Ojbr+vQy84xERUEh6lUpM7",
	"32LruLbSdhWthEO7wM70YIe6qY9L4mMJsxAT2pvRs/rAXZH7PhWTAVnDwHkdoZ/QahLp1GGRU7mDwA6+",
	"kHq5bjy0i8CdrqhYM+fQBdNS3JnYy1NjLW8Sc7L8huWqKUMtwTTzva6HQxxkyinSEZMswhEpxxNLFDD6",
	"d5n1YDIEjgxw0bxJ01r2dYLCNMZ0yAEHeBEBKjVnoQ8T2TN/EYEUXH0KG92lmOkExdgPCYXWqW7CTW0C",
	"RQObp3jvvcAkSjm89yw+utZc9zfUIQJpUVPdTTkhZeXCjiIRPEIn6FKjifwIc7IkIBCm6Oerq4tssUq0",
	"0SJVVNbF61IfTDgJABE56r4M7mSnpWVBPPSGAmLLY/Tem5uw5HsPMV5e6Qid68pIumTHSN/0PR6PV0SO",
	"rn8UI8KU/MUpJXIz1mWl6jTKuBgHsIZoLMhqiLkfEgm+TDmMjcbqzZwwKkZx8DeRgD/ENBjmV7ebm2dD",
	"bo2h6kjeasftrK9ztVNPM5vaZbOzhGQz/Rn0uuDuhHmeHTNOy6Gw2g31coFcZzVG3jGLX3Uk/18wbuIh",
	"2c2rPv3+TWT4b8wpoSvRPeY1k93gXYEsz4nbVkTaZnVTXHQX53VnmZvsujV1t3ng5Z7jTR3xPQfPyR9w",
	"RYxs3ieMWoYxt3cUXKqr+l1tEhAPmUgB2DKJsUWE0dPNLEm3rawphLVK3xLALH1tIzD6hhIBjhapLpEs",
	"Lq9NhofvPfXhaPij+fDP4fSp+TT9YfjkwHx8cvAPE7rdsgwTnXrEldjw19bFuNbwZPjUtj89Gk4P7Hqn",
	"B/8cHhzZ7gdHT/st9DXxc1XY5TIXG/T6bIZ0ULi0MIuqRdKux/x32IZwHqovW7IdBZBpafn3UGZatl/G",
	"x9gldkzclS0t9WYFMVn+YMx97IEd7TIDyc5KGjmO721dt+2ivbbQO++fqts8xByC50Rcd9Z3K93Q7nyI",
	"14CwRBFgIRGjgISGgJTN7Vmf4zVXNSg2x4yS+YZV3vmqDGuRZJfuOTfp1jPoo79Oo47Lprah6/D4gBx3",
	"caY14la8DeI++z36ioUIP17bQ6YrALOTOqD6UuPWTJuubtrmzBdlYbdtfkrdn2lMpCVd9zptC70rOEiQ",
	"P9QZCl2dFtce1DbbL7a/jvP9oEuF9TG1ANxHWS3qxRQfOjy2R6GCbrCZxN2RosWa6cmyGEJ2Oa6bTNmE",
	"g8oqP3TuYvWLua0Z7yJL2xJnXnEcwCWoQzbQALelB207BOjNHNlRmsTnV+9QKRmsmjVpfEzRArKuAZIM",
	"YVTutjWG7VuquBLNpQ2YgyArCsEw5Y7yIfiUEA7iI5bOm2ekXAqS1c2+vXyFJLsGHfrpl2Sxc1fhX3AY",
	"Gtw0SAVebdgRw0F2ZdAm7wIifLYGvkEkxisYbaWNmq9JjVuTx9ESEhEfbP2LiUF6Jwn2Q0AHo4lnEfay",
	"aMvNzc0I6+YR46uxHSvGr85mP72e/zQ8GE1GoYxNkJRIXftR1NFc2PtFJxdnpRfujr2UBrAkFAItuwlQ",
	"nBDv2HsymoymunRMhppHY5yQ8Xo6LuoqzJUkcPDsFRESlTtqyNahDGyHk0p7gjmOwdTZ/8fx7pGE8nNH",
	"2oe3bNE1iWo7935PQUdeLCnz97EG9u3GHlGg2w/6Jr+uStLrO5hMslv1NgWIkyRSXgRhdPybjS8W8Pu9",
	"DKWj9VoSajUQ/1JcOJxMdzanuXvrmOotxakMGSd/GNYf7XChrZOeUQmc4sjewtUbrt7q/1Ou1/mgXXZX",
	"oZ1JdCFMq68tVYXLdDopd7C1BKcs2DwCN/UTXrVqOOVP3TZkafoIs7vobEgQGGH6DHw9xQHKqiP3Aux9",
	"UN87DOb4N7YQ4z9JcGtEOwLXy2QzXYGLMPqNLZrCrRt/0S2dNrMoFzVgtIVU1rwwkNoAVkXWaSrb6rwf",
	"1ViqJXZYyP8SoT6cPHn8SV8wviBBANTMePj4M75m8gVLqV3iPx9/QnXCi4hxRr+0oVD6qLY4p+v0EqS+",
	"m5Fnwarq/xLkXvf3uv9X0f2vQxVbNuvsHWJ1XO3tjZoHX7IrREsSgbkrFnJGWSr0JS6Xu2pH9PRa4zSS",
	"JMFcjpWiDrOXTO7qOpafoO3lvx48toqf+D4kEgJ7ucnf+7Ffl05s812f6++3HNBMp4qo99zOKkAfsKt9",
	"0cP/fmvbb22fPZ7S6mzqAGcCPlkSfbmsVWtfgtyr7F5l9yr72UKgqWx9tr57gzWdvlZtfcxQrK1c7+XM",
	"7g3F3lB8C4ZiDnwNHP10r4izctjH9mLosPLTDu3H2vxNAddPQpjnT7oTMBmAQi8cD47/1Y1Sx29zfGbz",
	"1PXauytWuu299+Lpkr1h+/YNW+ltGsokWn5Rb0hN+xmorEwq8QG9pcWTjPeyrHkN4rD0qEsPy9r6Isxd",
	"zKvjRZVv16jm75VUHsEpvVhzO+jJ9Y6Xe3ZmeEvYVh6euWBCDouim1kI/nXteW/vyL7Gkl1PU5qmq9X+",
	"Dz2djPTj2AIB9kM0RtMJAroiFBQ79UU9xvEKUD5FDXbxtHcOvc/r27fNR2ryZ2MeRvf2bebc9WDRfpvZ",
	"bzNfR9lGVqLXGjiLtzzd3Yie2R+hfTQ3z1x/aDt/fmk6a3pWKGzq80RXOiGw6QTkm5+QtJd4spHuxMI8",
	"b300UufPFu4r+AoOZ7/W2hZt1lWhbaxTjZ+DccVjCXvmtTCvO9ltOdiSxp5njY9xoq48dvKZ6y2zJzP2",
	"tZZflbQ2t5PeKeo2QS5vIv2PUzmwbyvF1S7W+6j1Pmr9oAnv4Bk089AtuvkS5F4x94q5V8xH8/06cs4t",
	"Omlavza1fCzv88skmNutgcEnN5h7y7C3DLtPNG9zt8f6Qqx+Xwqw4+n6nwEHWuvfvDsxl2cbVkR1ObMt",
	"3SYk+HI7e8dG3Ec9eonzdvHbKi53Za/hyBbuZje3Ox24nL9oTTB6e/mq3YN7bi9Zm06dLDcDkObUt+XF",
	"Ve+9u2yavsWe3zgvKch/lyU//EInk62iX3lasMM5Kr/85/KPzkrtf1kXqb7Ur9RLKjFr7y/t/aVH9pdC",
	"wJEMW7dO04z8EPxrl1cUabXv542UULCzftD4C42osTbmTZGxd/vh9v8DAAD//8PiQ/vilAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
