// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbONLoq6D4naqNzyfJki1nZrzlqmM7l/FsHLsiJ/tjnMpCZEvCmAQ4AChbs+Wq",
	"8w7nDc+TfIUL7yBF23KSmdWfRCZxafQNje5G89+ez6KYUaBSeIf/9oS/gAjrn8dzoFL9iDmLgUsC+rHP",
	"AUsIjvWrGeMRlt6hF2AJfUki8HqeXMXgHXpCckLn3n1PdQmASoLDjzxU3WotSFAaLUlI4BpISCwTDQXQ",
	"JPIOf/Uok32fUQq+BNXlFhNJ6Lw/Y7yfTyu8ngecM+71vDmWC1AD9gkl6mWf0CVQyfjK63lJ3Jesr1bj",
	"9TzBEu5Df84oeJ8bwTmjM+ZcVBIHD8XUErggjDqGu+95HH5PCIdArVvjx6KjBEgV270CwYog5XPlK2PT",
	"38CXCg5N+0vO7lZ1BlhIGVs6RoS+AzqXC+9w1PNoEoZ4GoJ3KHkC1dX1vLs+wzHp+yyAOdA+3EmO+xLP",
	"9ahLHBKN9kOPRURSEvYSHvaExFwKyuQtkYsjNbXQuNC/vjIUFRAoyxD0vBBE+O5oNBwOvXs1bZ1WQoAQ",
	"0aaEtaMoUhyBk+vZLQX+hnAh39smAQifk1hqxvYu1Pu/CTRTTZAeptcwyju8bpAQt4whKI7FghnFRiRE",
	"+sf/4jDzDr3/2s0V367VersT28PL8Yw5xys9mlYGZx0VlW58pR/nyqqoaPhSMqYVk2nrUDAukbdrLYxf",
	"FvB8zZ9bWeUN41GdXXIA1yDqLGvYyArd+TxdZA9n4H3RY94/De1llpnod4jNkFwAyqdCAZb48Jqi/43+",
	"la3/X6iPzjFNcIiyZyiJQ4YDtCQY/TK5eG+6YKUpVfNTFoZ6F0LTFbqIgU4WZCbROZlzrEBAx8GSCMaR",
	"7nFNvd7TEcYosNlRDqEe2qiJIufUmaadOd4RITvLTEH9OKQmf/vBMLyb8WYkdJDsDQkhxfpMYa5MNK+X",
	"c8SUUKzl6qk4NardqXSUKqrzzyboWGd8NwU1mtpp9zE2g1eBN88VGqP6GgZer0KQ7wIDtWWehomQwD+Y",
	"Xqq1UL/BsGsZVvsCxXiVMZCPQz8JsbIQkW/GQrwwWA0NtpFRP+Xxz16lmEhHkiybAErDqrk3xZo+o5Kz",
	"8DLEFE4vP9bhOr38iHzGQaAYOLLNUazaI8oCQC8CmOEklIfo5U4OFaES5sAfaJ5AFMtVLyL0aE+bKXva",
	"SilDeQ6R3VHKgJrniFD09mQ9rKNNAjvWwB6M9mrAvmcBnLKEOhjqfRJNgSui1wEVh2iEGEf7BYj3FcB2",
	"6x/19j9vBHqj8Udovwb5xF9AkFjDswr7cRiyW3TL+I2WBWHaKjFg1LWcwjJmOBRQwP2UsRAw1ee6OLlY",
	"Aj9lUUTkB7XLmZl1T+/QGx2OvZ6DPdkSeN/XvZDeHNELGMwHPXStulx7BcR5o8OR1/NGh3v637H+92Xd",
	"WFK4VF36S8yVAhGq72mcXFC4YhdUKc/0r6tbVvjrDUt44c8JuVODP0o0F0xICE4LNHFojRnSh4IK0olA",
	"pjeCOwmc4jBcDdAZVfstlmQaAlKnj0qvGYEw6EirSEvbGnLt1chlhbSVYnvtFOtGKzNRgVyFB4ZihQea",
	"aI8lk5IC4FrQ1+tP01gLxVPUT7bP1VVlDs4aRfni7cnOs8FU1og5TFcLDjgQbdpQIUyaZlXw0Au1607O",
	"r/Kdl9GdATqbIcokijlbkgCCnjImkggEoky3fpGOd2RIsTNA54mQaAroOhkO9+EIlam4uW2sbnvlNoBT",
	"4zWJVpXRHJT+3NXEETGjwqFNTh02TBHViINIwma7ZkL+UAK5xsI/LTW+7+XHxCsmcSg6HxZtc41fcxg5",
	"ZVQkkV3OmrO5nv6Do2MDwSy87snqi2ghRo6mihdiCRyHYWYACt0OiSSKzGGkgvSKnSEeaGPUufy+580w",
	"CZV2Xjtg2tBu8DgIwJ6qlpiEeEpCIlfOKaRCkFNXatShXGNinzMhkMJJM8R6uCZdZ0aMChqv+5gNKDBD",
	"0gwR1sCxauq/y5jecQ6fS24riguazwVmhU0LMJdn6Dk4pUroAlXKGHWyMYviEO6IXL0i4maiaPWaShf6",
	"LyggUK+UWa7ONgERN8jP+qMpB3wTsFta426hhnWoqLyvboFmnEVopA5L4x66XQAHNFL2j5otBCxkOp2Z",
	"e8aYjDmhEmEaoHHaMmJ5wwHSS0KjQ7M7+EejIbo6MduLIIxC8Hc7+V7WZE81SR/vZ48Pio/H9jHop4Oi",
	"z6bKexPyB1ydNDFfARIkJON4DgrBVydaAD+dC4QlkgsizMRFx0bAEmXRZxMbPtaxgmjtQaU4sl8hxHoG",
	"TZulE5WX2s5oF5P3OOrMZTHw/sWkr4xBJ7PV/RNMuB3DVwtAFxPtEkZwh30ZrhAWiEiE4xgwF2rKZSQG",
	"TIdLjBmLrr0PEKCfsUSvqQQecyIAvSM0uUM/oRcvx/0pkTvX3s7A4ba773VmfSwEmVPjITwN1V+z1cVk",
	"gIboCCXUN0+IsodG6KgsDD00Rkdlrm9gx45swRNK1WaleeNiMljPDhblvRpfrOOEBymci8kzqJthVd3Q",
	"gPhYgkvrXExU40i7bUErnWGhPaa6wQKrDkkYaDt2Cign3hPpsjlxdZHlFZZYKSCou2CVtjV+rhp/zzjA",
	"KY6xT+Tq7UmhSWF5C8yDW8zh2PchBIW74Jwti3GBwmFUnXWdPjUduJwRgw5FG9XSkk2jJUgXoDYCLCX2",
	"Fzru2x5zU+dfFoA79hxzJpnPwjRsUGtgdto165dNvZdAA8bXR3SlCeZUJ6thPxuxl5KsGfmVxaVYcHHG",
	"ax0er3FFBELguUPQdHuUvl4Xu0rbfVYzCUkifTx5BRKTsD62eQ4BgqypPckYccZIEDoPITvqaGxU2Dkx",
	"YRcH5GZQCFDaRu/CmdTpcwd6ETNldOQzCMRouNKOjjusZNM79PYX42E0FK49IcJ3rxpBOMd3JEqidH1F",
	"UF5wTOcQrJt4P9prmJfQlnkJfdq8PzZNywELJ7LvlFltpmAztGC3WqwLhL3F+ZEVgrWcZCdysfDPREg2",
	"5zgyYMQcfD2kVQkV/sASl2JcTSKdx7IiQj/hMAF3ayEhdr2pSkI6iO3RM5A418OEK6QfJ6fqsLXOJaNP",
	"ZM2asQC5HycT5t+AXDumsM26jEoc+v0jJb8ngEiu5jPJU4reyc/6WHPuMK0VetKTIqHo/KRoNhMqX447",
	"wdm8MXTV3Jk+btauaY5QxfhpiRITatZinBVlFtBh3rdEGneTw9uv3qM50UZNRCRaYLEoybF/gEcvX47G",
	"Lw/w3sF09IMPANMffghG4I+HAUwPfgh+DPB43GVn1dB8MslEbqPcwGPzjbRt3kNTLCBAjGowJZ6XwBsO",
	"RoNxfzzszy2gXeCYNyPk7WZQ0ZSu5V71p6ett53n8sWWoWhgPo4disR4rcQlcGUW+qCOPg9UiSV/aJqC",
	"VPenqzZ+1gZpB+kAnWZaXx3RtOGDjsOQaa2NlqeXHwXaReYEfblYCeLjEJ1atdbhgJzZit0TgHL72LFY",
	"paIu2S3wiVRnAS2JQUDUOnF4WcJtI+ZyqqjRugOm94IGmBQFrafSvfM9ZI+r+LLdNP1wfJ5q3seQ1nZN",
	"aWv/tH7IsKP7g4K8ZfymOwrfmw6uVRuj28qDG4cNfp9ccpoQrFr9nNLadSzcHPlcDkYzdZ15CwgsSYpb",
	"gRTSwtxKpE0YOsUGFCK10FYM5Vg7w62DXUcL1fFcLoDwQmqWTQeqQb7MtdqDoLD9vpDWxI/lqRl9nbIu",
	"jNbLMdaK6VfWPK3m51lN3r4Y1aj74j/ZVRhmXNv6XNTXFwkdUFHztq4qjxdVUJoRUvOssGZhllpTs4Ae",
	"FZL4dC5SL1M+7ibjEw+ZQOFxbaii04AuqVejPyhEcBYvx6eMzsjc4RkyGQJvsYRbvColYpJ4Od5E+heJ",
	"x19wEHCT63ygFxVQ8dXmIvFxEHAQX29GkUwpyHMsbjaSOmuG+xJhcWOyC+px7HyNpdl7VfoazLuY5Bc2",
	"rfPsCfZv5pwlNEC/sanN01xRv5itqTOUnSeZrI3LHZhnNaKzV+h2AVRPYVyjypAQie+DELMkDFdFq6Ep",
	"PxhSJ1eLLwuRmVmIdkE1Z8iXh/iFTdHZK9cJ1OUpSG+xtCnaX9h0Yhq23f1oINMkm6IOpulpM55joAGh",
	"83+hPlLviEC/J5BAYN9iLuzbS/MTffh0xVgo0Os7H0I0IyGYppYpbesPNrpwcXmMPp2j9CWjwrTOSKga",
	"H1cYpUJY08OQI4XT/GVyojRR7bCY+hAW2hnnkn2oHfNplpJduOJIszJ1kMrWoGOwFkQbe9U/srGc94He",
	"4alxJZSZ/AZWG5HxUA+vuGFZcUM9fcwKiymQ02lcLJb5K/J4y6MTcaPM91GIeeQOwg3m5DrHt8m5+WE8",
	"YBEmtO//uJmU3cZsos54bcr+OW9HXHPyT9b6RCcEOBzwRNz0BfkDamEo0UMsC9nFwG2ULYQlhOjFqD/e",
	"yaLxXYL6WaS9Ja4vlCXHNRYCRc9iMF2PpgA9RCP0ohj93+mhvezJnn2ynz05sE/G9okJ8e8M1CkVzVhS",
	"WphAmAPC4S1eCRRzEEClCfN1Ong2pl+4HCoF2lxMHC7DyQNJMiyTpGvgMyXMA2OfBn1kCc+CvlIoeS3y",
	"3F65y3WpBuiihMyACEmoL7Osgpk2dcpW+d9EfhYdoNfYX9gRfMw5sdhOBzDKpIeIFMrUB078Gk3Ri+H/",
	"/7//b7zT0wFo1Zs6o/fksYjMszMceFRSNSF/wAetoB/o6KrcupJYEh+FjN0kMZJ4GgKKcBwr4EHhKchU",
	"jSTAkd6PFB+2YWeArhTuGZXKZiDCBhR8HOrNBZagUG93AIVADrMQfGno8MquLlMu6tSThsFSuuYzxti/",
	"wXMohfVzhc3EBpBU5EmbtZAt42JS5Dgi3Cz3D1gZKaszmijmwcgFrGwmTDkR5u9Ib/b5II2c6U5iQS8c",
	"SSz9MTpChCqjTtuO+Vg7hoQRjjUZMaGiosRqcleWuB7iMMc8CEGINLAYYbpKpSOTjArFqrtxdSusaeC6",
	"NBSJ7tQ5rRt7Hv3egMEkSQTPYyrlc3w9S6nn5XNNtM5y3OI0ukwByxM6QJ/USJZ3D9F16tTs63DLtddD",
	"155NuOuz2Uyh89rT+ecsIlLq1PMwRFZDauZXw5Z1aj0hpKIvY8xx1KIBjBu3Gvsz7QoBd6THAUULtgTO",
	"SQDCinaUCIkiLP0FuqHsltZ6Wddoms4mOaZiBvyL2su/RNNYGFwo3HxZsISLLzHwLwFemeeSaz+7WDAm",
	"v0SEmtfLyLyNmVBPLUd8ATonFICLa29ngD4K4H2RxHFIIKUEkvgG1FbvQwDUB70eNGVygayzQWi9nGmw",
	"fgCcLLP+A/SRmnXepIpNkBCo0mJkThmvpFk1SXc3W7sokrmt/RhvtuHO0nhJKOsK/3XNSFcLNTrVjGV0",
	"XkrOLly907BDZcs8EyJx5H3hUvmAeu2ONGmtKcJf6xGmp+B2p7hp1vNK90j9xsy18jK6R30qy3dIbxoX",
	"qvs9l+KWSH/hXGVj/QNZufQvJKYB5oHZSSQn08Q4FbLhe15ClQAxLhscC8sQ04bcvGUkTptI5M4wo017",
	"VAP3NiVQFblXe/3SrCyD+tpmlOdyPlK6aoljTkOqoBnzA3BtrRG+08729TlaJnjpyJgqOP4LSVOlDfJg",
	"sdeYH0boOgBsstZTABg1AVDPSipD48BQr0BBJ/vo2y/OG4bVSzOlq4QOB0WcuPMIatcQu4WKo/aLdY8a",
	"tbrVxEl2E6wFOx/c956q9p9ppEzjtFVK7LagmBNteTyMG7PSODTXIy0kEZHiYbey3pk+LSivx88eCBar",
	"89d6+KpM+UTqvctQ00A4i7sHEijr9QSWruO3+6gPRkpaLWcjZYceUXqmGhcplNfJIXBCbkru1G2htORZ",
	"a8GTua11Ukx8W5f09iL9IfF8R98BgsBEtC4+HeswhdKrypLrls5enPufmFPn/UT7ohjZsjPjEnABmc2A",
	"C5Nc7Secq5elJl1Aer5aU8SdwBan5bfWUssU6rrveUIsLpNpSPx/wNqen+whNZhMfs47aZOrYDK2jpA1",
	"dFYzeVy1JW03d7d/TUzKYfY2F/CilxwiIkq+q8LljQeXtWupY9VUm64AQ7P8nurODu2jfs600/p0gQnt",
	"TOjTasdNofsxt9EDsoSesypRN6bVKNL+qDxZ7gEM2/tG4uUqfNTMAg+qVGW1vkMWzJu8dNKWn2prSf1V",
	"f2K+qvNQQ5aEea5vmCEOMuHU+KVST2woTBQsYPRvMm3B5AI4MoOL+oXVxotUx2iRRJj2OeBAh0cKr1MX",
	"rUnZMH8RgdS4+kw2eMhVnGMUYX9BKDROdbtYVSbQwRXjeL/23mASJhyuPQuP9qPq9gY7RCDNaqq5uaBH",
	"WfEeQ57hO0DH6IMGE/kh5mRGTHjx56ury3SxirXRNFFY1oVBZOYURUQO2qvDOslpcZkjT0f62OwQXXsT",
	"k29y7SHGiysdoHN915DO2CHSpT8Pd3fnRA5ufhQDwhT/RQklcrWrr+yTaaKO4LsBLCHcFWTex9xfEAm+",
	"TDjsGonVmzlhVAyi4L9EDH4f06Cf1XKtb541vjWKqiUrV9tuZ12Nq40a3unULp2dZprW81qDThVvnWOe",
	"p6euk6J/qVKytngzrDXNPmuY5mm2ZHW/Ydx4F9OaW13a/ZPIhbXLRXuf90y2D+9K/PScsK0FpGlWN8ZF",
	"+6209vThOrlsxDlzYz6yv7mZ+8jOuqgBMbz5GN9kcYyJrf/iEl3V7moVg3jKRGqANZMYXUQYPVnlYf+n",
	"xKhfFcZMsxCmK3fyVpp6cvQx92v30OjoNRarHto7OoeAJFEP7R/9jHnQQ+Ojfyol+TZky2IBlsYFxck6",
	"Uj1mNdbDpstZEeBomujLjnmls2F/bGIvB/0fzY+f+qOX5tfoh/7+nvm5v/ffpiDammUY7+MzrsS6N9cu",
	"xrWG/f5L+/7lQX+0Z9c72vupv3dgm+8dvOy20PfEz2R7w+z3/uwU6ZhRYWEWVAukXY/5b9wEcMbGRdW8",
	"ofgSLSz/EdqJFhWyMZo2CR17cOZKw82oYk5Met31MQrO9nbptXhjl+84jh69XawzCzrZBA82CFSzyQJz",
	"CF4RcSPWlRHR55MFXgLC0ub5MQpI6BF00lXHmyRefVW9fLdPMZntwMWtvEywBk52yZ7T6mg8VD97/X11",
	"/jdZ+G2n4SdkY+eHdMNuefVz92H22VcsxOLLjT01uzxKG7mxUl1q1BiI1/dw1p1O8gtM902GV9VAq03U",
	"oZRXlnFcKOClz8Bqm91o4a404c8O3EVYLejtNYCqFuRGsaBf2ESDzaGiQZvpyVKnSFo/px1N3WuZ5btY",
	"NXu+MSEmT+JocJzPOQ7gA/gsioAGuCn8a99DgC4myPbSKD6/+oQKuSJ5OjamaAppU50lj1Gx2VqnvG+x",
	"4spDKWzAHEzyZz/hjosucBcTDuILls5CMKSYtZje8Pz44R2S7Aa0L6tb1MjOXUn94NC3ialqSDV8GlEz",
	"Zc4A2eBsQITPdG4tifAcBmtxo+arY+PeBKY0h4TEB5s2Zpyq3nGM/QWgvcHQswB7qfvo9vZ2gPXrAePz",
	"XdtX7L47O339fvK6vzcYDhYyMl5fInUeR1ulkOPLs8LXfA69hAYwIxQCzcUxUBwT79DbHwwHI33dSS40",
	"tXZxTHaXo908AUs/noODeu+IkKjYUI9sTcvANjguvc+SGYV3+Kvjyw46NzvvoVPfDIH0PTq1sXu/J6Cd",
	"Shap2bdAevY7VR0cXPefdQFYndan17c3HKbFWG2wF8dxqOwJwujub9Z1mo/f7dsXOhCheaKS7fIPRYXx",
	"cLSxOU2hLsdUHylO5IJx8och/cEGF9o46Rk15crNLTyz9epN/9diYt9nbby7cp1NDA9hWv6eRJm5TKPj",
	"YgObNXLCgtUzUFN/pKRydUtZVvc1Xho9w+wuPBsUBIaZvgJdT3CA0gT1LQN7n9Vzh8Lc/Y1Nxe6/SXBv",
	"WDsE17dXTvWtUYTRb2xaZ2798hf9plVn5hn7ZhitIZU2zxWkVoBllnWqyqa7yc+qLNUSWzTkfwhTj4f7",
	"zz/pG8anJAiAmhnHzz/jeybfsITaJf70/BOqs15IjFn6rRWFkke1xTlNp7cgdT2BLMBXFv+3ILeyv5X9",
	"v4rsfx+i2LBZp99cVAfXztaoyYpMy17MSAimvsmCM8oSoQuPuMxV26Oj1RoloSQx5nJXCWo/rU76UNOx",
	"+JG9Tvbr3nOL+LHvQywhsAU5/K0d+33JxDrb9ZV+vuaAZhqVWL3jdlYa9Am72jc9/G+3tu3W9tX9KY3G",
	"pnZ1xuDrW/htUvsW5FZktyK7Fdmv5gJNZOOHeds3WNPoe5XW53TF2qT8TsbsVlFsFcWfQVFMgC+Bo9eP",
	"8jgrg33XXgHulz5e3XyszSvguT4YqS/vtwdg0gFyuXB8p/KvrpRavj7+ldVT20dCXb7SdZ8JzcttbhXb",
	"n1+xFeqpUiZN+bBvZg2pab8ClpVKJT6gjzT/jMDjNGuWxt4vFNbqoFrXlDGta9lCHYcGbeuoBvrn1bFZ",
	"UZJSWbJCDbH7XkcmaCk++5X1cFu5VgeTrivYulXDWzX8faQ1aFWYabRHa8JKfcKHWJqO6mx/Yd3nKn34",
	"a7nsm/e5WGiwXuDPOxwNh8Oeo8Sfd/jy/uHKtV6ocmPKtYCO8hKrVcIumZD9XGueLsA3Vx9KX1f0DmyN",
	"q9K3D72RfZreh1aCp7OJ/w96ORwMUUSoMDVod9FoiLKqhuZmuPlIczZ3fdLxYt897aI2sSLMYDhEb08Q",
	"lmg00nMnEoSudHowHL490RJaL0pWqCBWLxiWVffSd59L5QBrmEwXdJG/Ly9nb+FczX7LWuxcEKhVLTEn",
	"+k45N+4a52qKk1TfmZmeyKhd9t6CPtqegbab7/ex+aaZ5I1Rne7fiqwFefQ9hme0gs19vSY36bfGuMZs",
	"CdcmjVy0Rb0DG/VGPgtD8NNbp2lPd/x7kr19NlRnX4TZJprnFDZUaQ6K6ssLTaRTL78G4fJyRVviNRCv",
	"PSfLUrAh22qSvnwOx2+p3NhXvhaQFq3aXgn4rri1vp10zqRqYuTiJtL9qJsN9ufKxGhm621wdRtcfdKE",
	"D7AM6ulSDbL5FuRWMLeCuRXMZ7P9WlKjGmTSvP3exPK5rM9vkwfVrA0MPJnC3GqGrWbYfD7UOnN7V1dw",
	"0BUeATs+cvUzYPP1vItPx6baQ02LqCZn9k27Cgm+3c7eshF3EY9O7Lye/dayy0PJayiyhrppqZFWAy6j",
	"L1oSjD5+eNdswb2yVUFMo1aSmw5IU+rPZcWVC7W4dJouu5KVSCkIyH+WJh9/o5PJWtYvFfdtMY6KtXdd",
	"9tFZ4f1f1kSqLvU7tZIKxNraS1t76ZntpQXgUC4at07zGvkL8G9cVlGoxb6bNVIAwc76WcMvNKBG25gi",
	"WLve/ef7/wkAAP//y68N7nW0AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
