// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LbONLoq6C4p2qSs5Is2XJmxluuOr7k4tk4dllO9scmNQuRLQljEuAAoGzNlqvO",
	"O5w3PE/yFS68gxRty0lmV38SmcSlb2g0uhvNf3s+i2JGgUrhHfzbE/4CIqx/Hs2BSvUj5iwGLgnoxz4H",
	"LCE40q9mjEdYegdegCX0JYnA63lyFYN34AnJCZ179z3VJQAqCQ4/8lB1q7UgQWm0JCGBayAhsUw0FECT",
	"yDv4p0eZ7PuMUvAlqC63mEhC5/0Z4/18WuH1POCcca/nzbFcgBqwTyhRL/uELoFKxldez0vivmR9hY3X",
	"8wRLuA/9OaPgfWkE54zOmBOpJA4eSqklcEEYdQx33/M4/J4QDoHCW9PHkqMESJXavQLDiiDlc+WYselv",
	"4EsFh+b9JWd3q7oALKSMLR8jQt8DncuFdzDqeTQJQzwNwTuQPIEqdj3vrs9wTPo+C2AOtA93kuO+xHM9",
	"6hKHRJP9wGMRkZSEvYSHPSExl4IyeUvk4lBNLTQt9K+vDEUFBMoyAj0vBBG+OxwNh0PvXk1b55UQIES0",
	"qcXacSlSHIFT6tktBf6GcCE/2CYBCJ+TWGrB9i7U+x8EmqkmSA/TaxjlPV43SIhbxhAUx2LBjGIjEiL9",
	"439xmHkH3l92csW3Y7XezsT28HI6Y87xSo+mlcFZR0WlG1/rx7myKioavpSMacVk2joUjGvJW1wL45cX",
	"eI7zl1ZRecN4VBeXHMA1hDrLGjaKQnc5T5Hs4Qy8X/WY908je1lkJvodYjMkF4DyqVCAJT74TNH/Rv/K",
	"8P8X6qNzTBMcouwZSuKQ4QAtCUa/TC4+mC5YaUrV/ISFod6F0HSFLmKgkwWZSXRO5hwrENBRsCSCcaR7",
	"fKZe7+kEYxTY7DCHUA9t1ERRcupC0y4c74mQnddMQf04Vk3+9soIvFvwZiR0sOwNCSGl+kxRrsw0r5dL",
	"xJRQrNfVU2lqVLtT6ShVVJefTfCxLvhuDmoytfPuY2wGrwJvnisyRnUcBl6vwpDvggI1NE/CREjgV6aX",
	"ai3UbzDiWobVvkAxXmUC5OPQT0KsLETkm7EQLwxWI4NtZNRPefyz05QS6UiSZRNAaVg196ZE02dUchZe",
	"hpjCyeVHA9cMJ6H0Dl71KjCeXH5EPuMgUAwc2a4oVn0RZQGgF7bvAXr1MoeQUAlz4A80VSCK5aoXEXq4",
	"q02WXW2xlCE+h8juLhnQoxrUphF68fb45Xq4R5sEfKwB3x/t1gD/wAI4YQmVJdj3qqB/SKIpcCUYdaAF",
	"ejHSUigInYfmWQ/t6UfvjhQW1k4Y9fa+bAQlsz2M0F4NnYm/gCCxVmoBoRkOBVSROgpDdotuGb/RC0mY",
	"vmoNMerCM+fHlLEQMNVnwDi5WAI/YVFE5JXaEUsTe6ODsecSX7YE3vd1L6Q3UvQCBvNBD31WXT57Bbp5",
	"o4OR1/NGB7v637H+91XdsFKkVF36S8yVshGq70mcXFC4ZhdUKdr0r+tbVvjrDUt44c8JuVODP2oZR1rG",
	"11Bk12tYGq1E2W0nSjdymIkKFCk8MEQpPNB0eSwllFwB1+srVWfNKsw01mL2lFWfbTt1bZWDU9RVberp",
	"OWAqK6IcpusFBxwIx86cKR5FMGmaVcFDL5SumZxf5xshoy8H6GyGKJMo5mxJAgh6am9PIhCIMt36RTre",
	"oWHFywE6T4REU0Cfk+FwDw5RmYub20nqplC+JTuVStPSqgqag9NfulocImZUOMyjE4dJUSQ14iCSsNnM",
	"mJA/1IJcY3CflBqrE3tq/18ziUPR+exmm2v6mrPBCaMiiSw6a47KevorR8cGhll43ZPVkWhhRk6milNg",
	"CRyHYWaPCd0OiSSKzNmgQvTK9t66qlq3uVTK73veDJNQaee1A6YNrWmAgwDsIWeJSYinJCRy5ZxCKgI5",
	"daUmHco1JvY5EwIpmjRDrIdr0nVmxKig8bqP2UACMyTNCGFNI6um/lqm9Evn8PnKbSVxQfO5wKyIaQHm",
	"8gw9h6RUGV3gSpmiTjFmURzCHZGrUyJuJopXr6l0kf+CAgL1ChGqjxoBETfIz/qjKQd8E7BbWpNuoYZ1",
	"qKi8r26BZpxFaKTOLuMeul0ABzRCROjZQsBCptOZuWeMyZgTKhGmARqnLSOWNxwgjRIaHZjdwT8cDdH1",
	"sdleBGEUgr/ZyXezJruqSfp4L3u8X3w8to9BPx0UXShV2ZuQP+D6uEn4CpAgIRnHc1AEvj7WC/DTuUBY",
	"Irkgwkxc9DMELFE2czaxkWPtuo8K5wO3QBZH9iuMWC+gabN0ojKq7YJ2MVFH965SFgPvX0z6yhh0Clvd",
	"XcCE2097vQB0MdEeWgR32JfhCmGBiEQ4jgFzoaZcRmLAdPTCmLHos3cFAXqHJXpNJfCYEwHoPaHJHfoZ",
	"vXg17k+JfPnZezlweNHue51FHwtB5tQ47E5C9ddsdTEZoCE6RAm9oeyW9tAIHZbXQQ+N0WFZ4BsksaNE",
	"8IRStU9psbiYDNZLgqV2ryYS64TgQbrmYvIMmmZY1TQ0ID6W4FI4FxPVONIOVND6Zlhoj6lqcEvkImVW",
	"AdwnsmRzi9TFkVMssVI7UPeDKh1rnE01qZ5xgBMcY5/I1dvjQpMCegvMg1vM4cj3IQRFtuCcLYvO+cKJ",
	"fMGEdDq2dPRwRgw5FFtUS8sxTZYgRUCpfywl9hc6+Noe+FKnXhaAOwAccyaZz8LUd19rYPbXNfjLpt5L",
	"oAHj68Oq0kRUqpPVqJ+N2EtZ1kz8CnIpFVyS8VrHqGtSEYEQeO5YY7o9Sl+vCyCl7b6omYQkkT6UnILE",
	"JKyPbZ5DgCBras8vZiXj1I+VHnA0NSrinJjYhwNyMygEKG2j995s1enThj6vRliqZljkLQ1+2slxh9UK",
	"9Q68vcV4GA2Faz/ggIUThjtlY5oh2Qwt2K2W9gK+tzg/v2kJz+cbDYfDwXCI3h4rbTEaDVFEaCKtn2J/",
	"ONRS0s6QjDwZjC6heEeEZHOOI4NBzMHX0NhFVqE4lrgUumlaJHmIJiL0Ew4TcLcWEmLXm6pspYPYHj0D",
	"iRMfJlyR6jg5UYeWda4NfbJp1jUFyP04mTD/BuTaMYVt1mVU4tCYHyn5PQFEcsWZybJSnS6ZNEeqc4eJ",
	"qsiTnrgIRefHRfOTUPlq3AnOZlXbVRdmGq5ZX6WpLxVLoiX4SajBxUh9WQR09PItkcZtUx9XJ6WgOdEW",
	"QkQkWmCxKC1Kfx+PXr0ajV/t49396ehHHwCmP/4YjMAfDwOY7v8Y/BTg8bjLXqWh+WRyZNzGrYHHptFo",
	"G7eHplhAgBjVYEo8L4E3HIwG4/542J9bQLvAMW8myNvNkKIpC8mN9aen4dsuczmyZSgahI9jhyIx3h9x",
	"CVwZWj6oI8QDVWLJr5hm1tT90qqNn7VB2tE4QCfZhqE2LW1KoKMwZFpro+XJ5UeBdpA5iV4uVoL4OEQn",
	"Vq11OGhm1lf3vJbc4nQgq1TUJbsFPpHKsNYrMQiIwhOHlyXaNlIu54oarTtgei9ogElx0Hr83DvfQ/a4",
	"ik/YzdOro/NU8z6GtbZrylv7p/XnhR3dCBTkLeM33Un4wXRwYW3MWLse3DRs8J/kK6eJwKrVu5TXroPW",
	"5tjnctSZqevCWyBgaaW4FUgh28mtRNoWQycfuyKkXrTlEBKOtVPZOqp11E2ddeUCCC9kHNkslxrky1yr",
	"PQgK2+9X0prPsDwxo69T1oXRejnFWil9as3TatqZ1eTtyKhG3ZH/ZLEwwri29bmo4xcJHZhQ87Zilcdd",
	"KiTNGKllVlizMMsYqVlAj3LtfzoXqcsmH3eTfv6HTKDouNbl32lA16pXoz/I1X4WL8cnjM7I3OFrMZH2",
	"t1jCLV6V8gtJvBxvIquJxONfcRBwk8K7r5EKqPhqc5H4KAg4iK83o0imFOQ5FjcbyQg1w/0aYXFjovT1",
	"eHCOY2n2XpW/hvIuIfmFTesye4z9mzlnCQ3Qb2xq0w9X1C8mIerEW+dJJmvjcrDlyXro7BTdLoDqKYyz",
	"URkSIvF9EGKWhOGqaDU0pb1C6jZq8Q4hMjOIaKdOc+J3eYhf2BSdnbpOoC5PQXo5o03R/sKmE9Ow7UpD",
	"A5sm2RR1ME1Pm8gbAw0Inf8L9ZF6RwT6PYEEAvsWc2HfXpqf6OrTNWOhQK/vfAjRjIRgmlqhtK2vrKv+",
	"4vIIfTpH6UtGhWmdsVA1PqoISoWxpodhRwqn+cs4tTVT7bCY+hAW2hm/lH2oXd1pto9FXEmkwUwdpDIc",
	"dCzTgmhjmPpHNpbzmst7PDWuhLKQ38BqI2s81MMraVhW3FBPH7MiYgrkdBqXiGX+ijx48ej80ijzfRSi",
	"CLlvcYOpps7xbc5pfhgPWIQJ7fs/bSYTtTErpzNdm7JoztsJ15xEk7U+1oF1h0ubiJu+IH9ALbAjeohl",
	"8a8YuA1ZhbCEEL0Y9ccvs6h2l+B4FrFuiY8LZclxTYVA8bMYlNajKUAP0Ai9KEbRX/bQbvZk1z7Zy57s",
	"2ydj+8SEyl8O1CkVzVhSQkwgzAHh8BavBIo5CKDSBM46HTwb0xhcDpUCby4mDpfh5IEsGZZZ0jWKmDKm",
	"eyDRUI4s4VkoVwrJrqWb2yF3uS5ajy5KdAyIkIT6MgvMz7SVUzbIfxD5MXSAXmN/YUfwMefEEjodwOiR",
	"HiJSKCsfOPFr7EQvhv////6/8cueDuSq3tQZBSePJWSe4LCOjsKtHU5YNCVq9V1M/nralGfTLpQaw1Qs",
	"izKmMNQShmkmZBeTgpooCfCCzBeQi/DDxBDpOIyOotmYu07p4NBXwyXKDDEUKATofRYmEUUxi1PvlkSE",
	"zpXSZRRJEsEzS/c5lpzctXlbnuCSrMY1fa1mUaTnRIkArX8D4Iq8eg20SIIm/wBdJGobvoGV4YFLf6Xy",
	"8DdEKC02DlxDCvRiZJsvDQMxN9CY/U5fWUnhskB8FICYuNL2hvYfcRAsXALC6NP5D0JBZTNdqNlTJuQP",
	"cDRX69ZsOap1T81KlUjCnQliWUpJhmbELt4MlIaciwL1y/M+jJeVK3wSS+KjkLGbJEYST0NAEY5jRRtQ",
	"KirINnhJgCNtBSqw2xTTAF1rfKhUljoRNozn41CbdLAEpfWs3aUIyWEWgi/NUj212GVbOp2ReRqnTlVq",
	"PmOM/Rs8hwZSZbx8CpGK24FNvMnQuJgUlT0Rbm3/91RQ6zpeFLO45AJWNo+rnMZVE+HGTcGdgoVelFOw",
	"+mN0iAhVpyhh14Ed5qXhXoRjzUFMqKgo6NpuV97neojDHPMgBCHSJIAI01W6J2X7UYVZVfO3anvWTJ76",
	"Qijy27nTO7cth9ZstbjzRI8NnGTUTvA8Z5h8ju/9CFMk6PojTIVijYeXPL3ukRGHWkJPTTEcp1MoRhRA",
	"mq7KKTw11E1EqDGVx3h3IUvoyVmZJey05vH0UHp3aXexN4zs7aWM6WP10JXY43IQn+YZNTlFW9l5JkTi",
	"SMTDpaIK9YomaRZhU4JIrUeYOlHasTDNel7pdq3fmEpYRqN70LCCvsM2S8OKdbf5UtwS6S+cWDZWhZCV",
	"UghCYhpgHhi9KDmZJsYnlQ3f8xIqkjhmXDb4pZYhpg3JkstInDSxyJ3yR5vSDMxtE+dNverlk9KVPIeD",
	"Ik7ceQS163zdQsVR+wW1R41a1Ylxkt2oaqHOlfv+UHWbMY3UTp22SsNMbUExJ9nyeBg3u5dxaK4nWkgi",
	"IsXDbje9N31aSF6Pnz0QLFaXr/XwVYXyidx7n5GmgXGWdg9kUNbrCSJdp2/3UR9MlLQIzEaq6Tyioko1",
	"LlKoGpND4ITcVJKpb2ZpJa/WOh5zW8Lj+WoGEXfGVpyWUVoLnim4dN/zhFhcJtOQ+H+HtT0/WeMvmEze",
	"5Z30JlHY5FpHyBo6q1I8rmqO3um779gmCOPYqJsLMdFLDhERpWNjIf//weXJWuoRNdUYK8DQLLAnurNj",
	"uamfM+0XO1lgQjsz+qTacVPkfsw15oAsoeesLtNNaDWJ9Hkwzw57gMD2vtHychWwaRaBB1UcsmrOsRbM",
	"m7wEzlaearhcxOZk+SeWq7oMNaQFmOf6khLiIBNOjWMq9XCEyvDEEgWM/iDTFkwugCMzuKjfdGy8i3OE",
	"FkmEaZ8DDrRnsvA6dX2YHAXzFxFIjatPYYOHXFs5QhH2F4RC41S3i1VlAu3XNI6vz94bTMKEw2fPwqML",
	"QOj2hjpEIC1qqrm540VZMXE/T2kdoCN0pcFEfog5mRETT3t3fX2ZIqtEG00TRWVdUULqgwknASAiB+1V",
	"Pp3stLTMiafjW2x2gD57E5Ng8dlDjBcxHaBzfV2NztgB0iUcD3Z25kQObn4SA8KU/EUJJXK1o+96q9Mo",
	"42IngCWEO4LM+5j7CyLBlwmHHbNi9WZOGBWDKPiLiMHvYxr0s5qc9c2zJrdGUbWkoWrD7ayrcbVRSzOd",
	"2qWz09TKeiJn0KlyqXPM8/SYcVx0hVVKjxavQrXmlWcNU/9VSxrzG8aNPyQth9Sl3T+IXPwDc5q665v7",
	"fGCyfXiXI8tzwrYWkKZZ3RQX7dew2vNl6+yywZ7M8fLI/uZy5yM769vwxMjmY9yoxTEmtnDIfUNU63oV",
	"g3jKRGqANZMYXUQYPV7lcdWnhIdOC2Omsffpyp2tlIa1Dz/mnrgeGh2+xmLVQ7uH5xCQJOqhvcN3mAc9",
	"ND78h1KSb0O2LFbuaEQoTtax6jHYWJeSroNEgKNpom/35SWyhv3xZ0/92O//ZH783B+9Mr9GP/b3ds3P",
	"vd2/Gl/0GjSMu+0ZMbH+vLXIuHDY67+y71/t90e7Ft/R7s/93X3bfHf/VTdEPxA/W9sbFr8PZydIe7kL",
	"iFlQLZAWH/PfuAngTIyLqnlDHnFaQP8R2okWFbIxmjYJHXtw0LjhKlAxHJ3e73yMgrO9XXot3thtM46j",
	"R28X68yCTjbBgw0C1WyywByCUyJuxLpKFPp8ssBLQFjaxDZGAQk9gs536Hh1wqtj1ct3+5SS2Q5c3MrL",
	"DGuQZNfac1odjYfqZ6+jrs7/Ju287TT8hPTj/JBuxC2vYu0+zD47xkIsfr2xp2aXR2kjVzSqqEaNoUN9",
	"8WTd6SS/sXN/35JOVDTQahN1qAGVpdgWKj/pM7DaZjda8SnNtbEDd1msFvT2MjJVC3KjVNAvbGh0c6Ro",
	"0GZ6stQpkpZgaSdT9yJY+S5WTRdvDOHnYecGx/mc4wCuwGdRBDTATfFO+14nEiLbS5P4/PoTKkS3dY6y",
	"Io2PKZpC2lSnJWJUbLbWKe9bqrgi54UNmIPJu+on3HGzA+5iwkH8iqWzaAop5rakVxo/Xr1Hkt2A9mV1",
	"ixrZuSvpaxz6NidMDamGVxt2yHBgimQBstHIgAif6bQ2EuE5DNbSRs1Xp8a9CUxpCQmJDzahxzhVvaMY",
	"+wtAu4OhZwH2UvfR7e3tAOvXA8bnO7av2Hl/dvL6w+R1f3cwHCxkZLy+ROpklrbSGEeXZ4Wvshx4CQ1g",
	"RigEWopjoDgm3oG3NxgORvp+j1xobu3gmOwsRzt5yoh+PAcH994TIVGxoR7ZmpaBbXBUeh9jjiMwl6H/",
	"6ajQr9Mi8x7KmrcM0hfH1Mbu/Z6AdipZombfdOjZ7w11cHDdf9GVQ3XClcZvdzhMq3ja6CaO41DZE4TR",
	"nd+s6zQfv9s3DHQgQstEJb3j74oL4+FoY3OaWk+OqT5SnMgF4+QPw/r9DSLaOOkZlcApDs21M7P16k3/",
	"n8VUpC/aeHflEJoYHsK0/F2AsnCZRkfFBjZN4pgFq2fgpv7YRCXRT1lW9zVZGj3D7C46GxIERpi+Al+P",
	"cYDSxM+tAHtf1HOHwtz5jU3Fzr9JcG9EOwTXNzRO9DVJhNFvbFoXbv3yF/2mVWfmmbBmGK0hlTbPFaRW",
	"gGWRdarKpsu4z6osFYotGvK/RKjHw73nn/QN41MSBEDNjOPnn/EDk29YQi2KPz//hOqsFxJjln5rRaHW",
	"o9rinKbTW5D6An0W4Csv/7cgt2t/u/b/U9b+97EUGzbr9Nt56uDa2Ro1dyHTOg8zEoIp6LHgjLJE6Eob",
	"LnPV9uhotUZJKEmMudxRC7WfluN8qOlY/FhaJ/t197mX+JHvQywhsBUo/K0d+32tiXW266l+vuaAZhqV",
	"RL3jdlYa9Am72jc9/G+3tu3W9tX9KY3GpnZ1xuCTGdH35hpX7VuQ2yW7XbLbJfvVXKCJbPzAavsGaxp9",
	"r6v1OV2xNim/kzG7VRRbRfFnUBQT4Evg6PWjPM7KYN+xd177pY8QNx9r85Jvri8N6hqV7QGYdIB8XTg+",
	"cPifrpRaviL9ldVT29clXb7Sdd+XzOtLbhXbn1+xFQqIUiZN5Z5vZg2pab8ClZVKJT6gjzSvm/84zZql",
	"sfcLBWs6qNY1dTvrWrZQuKBB2zrKX/55dWxWmaVU7qdQm+e+11EIWqqtfmU93Faf1CGk6yqUbtXwVg1/",
	"H2kNWhVmGu3RmrBaxeoBlqajbtZW9xU0Tr0+28Z0XwHaUnmxSyZkP9dhJwvwbyqf6/P2bc2t9BKyknad",
	"wvt/0KvhQH/sTpiaiztoNERA54SCYqe+jm0+qZtNURk7/1RfNnqXr+nd10uRZcXBnkb3Lpq+IP1bi3ur",
	"6r8PVZ/mLTfGELp/iq8WUtBZ889oc5nbYU1OuW9NcU3ZEq1N0rJoi7EGNsaKfBaG4Kd3HNOe7mjrJHv7",
	"bKTOPrixTWvOOWy40hyC06nyTaxTL78G4/LiOFvmNTCvPQPIcrAht2eSvnwON2OpuNVXTkJPSyRtE9C/",
	"K2mtbyed83aaBLm4iXQ/WGWD/bni/s1ivQ3lbUN5T5rwAZZBPTmnYW2+BbldmNuFuV2Yz2b7tSTiNKxJ",
	"8/Z7W5bPZX1+m6ybZm1g4MkU5lYzbDXD5rNv1pnbO7pegK4nCNjxqZJ3gM1Hji4+HZnaAjUtopqc2Tft",
	"KiT4djt7y0bcZXl0Euf14rdWXB7KXsORNdxNC1u0GnAZf9GSYPTx6n2zBXdqa1CYRq0sNx2Q5tSfy4or",
	"lwVx6TRd5CMryFFYIP9dmnz8jU4ma0W/VEq2xTgqVnp12Udnhff/sSZSFdXv1EoqMGtrL23tpWe2lxaA",
	"Q7lo3DrNa+QvwL9xWUWhXvbdrJECCHbWLxp+oQE12saUXNrx7r/c/08AAAD//+bPtdarsAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
