// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+wa224bN/ZXCO4+tNiRZStOdivAD7aSNkIrx4hs96E1Amp4pGE9Q05JjhQ10L8vSM5V",
	"4khjxQ52F/uUiXl47nfqCw5FkgoOXCs8/IJVGEFC7OflArg2H6kUKUjNwP45lEA00Et7NBcyIRoPMSUa",
	"epolgAOs1yngIVZaMr7Am8BcocA1I/GdjM21HQhGG9iyjFEfIqWJziwXwLMED3/DXOheKDiHUIO5siJM",
	"M77ozYXsVWQVDjBIKSQO8ILoCAzCHuPMHPYYXwLXQq5xgLO0p0XPSIMDrEQmQ+gtBAf80MrOmM+FV6gs",
	"pU/V1BKkYoJ70G0CLOHPjEmgRm6rn1wdDUa2tR3UDFZnqaJVSSZmf0CoDR/W9jdSfF7vOkCkdZrbMWH8",
	"F+ALHeHhWYB5FsdkFgMeapnBtnQB/twTJGW9UFBYAO/BZy1JT5OFxbokMbNqH2KRMM1ZHGQyDpQmUisu",
	"9Irp6MKQVlYX9usbc7HFAhelgl6Wg4R8vjg7PT3FG0PWb6up9YC71F31xOy+AOzOUuGCRitWCS5Exh3C",
	"9wgiJfJNI/a/Hq9DtTkQwkdgNqYaWEvtieWj8ToHqKeBbhmg4KRmLl/QvyWaKC2kx4EoU4/OyDspay4B",
	"RiQlIdPrn65qIIxrWIA0MBGRdEUkXIYhxCBNCpqIJdSAZ0LEQLgFFko7WhRUKFmqrRbx2Mo0ZyCRmCMd",
	"ATKQaBWBBKQjphAtBEBMIaI1CSNbFPYH5CbAiaDgL0ypFFqEIr61Bx4ALTSJD8mv224vgVMhD6d7e7pL",
	"bEf7JcagMFm78reEK7Tg84x3tnbueEUCSpEF7JrKwqPiODggXAH3sAnwe6a0WEiSOKSphNAwXFhuyyuJ",
	"JuZfpiFR+zSPiZRkbS3N+D2JM/BDKw2p72Sb4QJJfiNwnPg0914oXw+VZiMhcyEamrvOkplz8NHNHQot",
	"UKsD1zgP02wqwkfQB3GqHKwLVuYJwzvO/swAsSoa50K6+DPx6OtqEkiEXE+udpEZ9SB3jBhHE+vSRRlh",
	"XL8578Rne/x2DbAybNqDYMznknhsGWdKg1Q3IE0CDYFrkE/0yjDNPixBjkSSMJ3kbXdTU8Z0BiYsYdBH",
	"opk4QSMSh1lsogQRhWyKQJdxLGzgoOXo5k6hPrq1f7+J1oqFJEaj3LOqtlRkRsUlb9w6jWGuzKqqIdXf",
	"JczxEP+tXw0Q/Xx66FeVxCOs8ZIbsQJpehaHlFDKjJwkvmnotlVzlVUMtu6M2XBs4clYcOSM6U8+T0kz",
	"1qUP2fTj5aRw/mNMm18tbJv/lywJc+HSyboc9ErIx+4qvHYXfFK78pTHg1+HHtWZS1XktCnYQL0vbL17",
	"vkyez3zbtbciveu8NQU2IsWfQIo5szWJ7AuGfUYpURtF2qBtONqEpCb951QQJwkYdzJNFJOonH9tA4U9",
	"nC+rrPYkLvJ7n3x1ZPy2aOOWI4f9UJ9QwxZUGtur6bd5h9DUNisy+X5hDFB34e9zKZwzHoSeqF35EuNE",
	"jjmvVOnyfCT4nC08DTrMSRbrn4iGFVk3pjGWLs+fYxpj6fknQql08+hryz7l6pvRYuklpRLUt6OoshkH",
	"PSHq8XnGTovuU0LUoxvodue5SsYG9WDbvk7zPif5hcxcK9T0j0dYP4sMsUVvx9utNvrrcW7pwrBckPFJ",
	"OmELacokHyuVeWZWohQoVVTe3aWkyBonO23vzo24UO3+NOXAgjr9gppPjKKe7ob0Uq2YDiMvLyaF++fR",
	"fNQsFqRKE06JpG4i1JLNMrcpLdEHOOMqS1MhzYFvz7mMCW+Z/peJGrUp0j/DWs59ipja3YTHjsUeel8+",
	"dcvqTeCg76vVS7PoWDCU70PQd8WHJovvka3cFK0i4OjD/SVaEYWoWPFYENptjVCn/SuR3Px5h4X8oJiO",
	"EZsXlEmDOcrmc5AKzaVIUJhJaQ4bIF1YOmJb33EXz/zjUFrsRA9ay21PTZpV0U02i1n4Mxy8eZ/nDzqd",
	"vq8uWUesBdJeDCWgd5vK6k1ap2anTA3de2iXpD0ddGtYC34jIWGqMRfVlmZPfmvwvSdY6u0PBjUe2uN3",
	"/yLa+u+4q4M93RLbUtVedgrSPtaL3m23U6SdnmK8OCcfwa1brySQR5NJPG8p9XXX3sG1BCyGoT1z0o9C",
	"uuLoUkM3uF+ZjvLcpPbfuRZ6P3rfAIW9vB1kpI2qX+PKM1mJJI3hM9Prt0X5yyvDMXMWZepxyv6CWwZy",
	"miUJceHfzPB1QmbGuZ8oNFujpOhXUMUTimEJcYCASxZGpvowHeWDvqGFFPsLUArSAZ6gaZaCVEBBIVoj",
	"c7UelThPfBNcfeO4fy7Z9dqNWyaXdf7I+245fuTlQunPbLgdPRm423UK6msIGQQHiHgt97RV2Fc6Hfru",
	"9OKuavwCdHbxjqh1gAYXE6AsSwL06uI9kTRA5xe/RkzDT7FYwvf4sEBpdshUx0hDQimUsjtszUCiWWYX",
	"2eg7OFmcBOh3fNo7/x2bj9e9f7mPH3pnb9zX2T97rwbu89XgH7/jDmJM7D7tBSVxBA4L45PhVe9Nfv7m",
	"de9skMt7NvihN3idgw9ev+km6DULy9h+Zve7Ho+QHX1qguWs5kzm8rh/ztsYLt24XqE6tVpbU6Kv56qJ",
	"f0R24vW69BGIEvw5uRPqqWZpWblWyhTle/cxCS6/7ctr6bNt9SVJji4Xh7qjTq3Rk/siAzaNiAT6lqnH",
	"va9wJjZ0RDSKyBIQ0SgGojQSHJCyGGzpx8GT+qpGU1VW+0KTZQWul/KmwVo82Rd73ubLO5i9+G9jlIo+",
	"PYLr/O+T1l2K3RIeGiOq9eqmrTXYbiF2CFlbWCjPa+ftVl/HOLq9qp5PTSHo9mizTMqMtc/JGG8g7uJO",
	"OesViYc9TdKLaMEe5Lui51NFS7xZYvYZwqgp/5HFfjUVBIOGlA978+z2SNK6eaz2cC1T/kISCh8hFEkC",
	"nBLt3XKV50DRhynKb1kVT27vUW3dZ46takLC0QwKUIq0QATVwQ5uEMJcK75VYqGTjdsbWZ3ELASubA52",
	"Ww98mZIwAjQ4OcUBzmSMh+5nfsN+f7VanRB7fCLkop/fVf1fxqN319N3vcHJ6UmkE7dTYdrkF/whBT6N",
	"2FyjssqiS7pkSkh0eTNGvXybBpymgvH6TyKHOOMU5owDtYZMgZOU4SF+dXJ6cmYSJ9GRtWWfpKy/POtb",
	"VKr/hdFNv/qlWpp5HNPtRpCDKt7A3JLTksobAlqC1n7gZ0lLkoB7LPzN86hWx8bM3wyvxXJn6BY9ld1c",
	"FnYpsMNWZvPgLoPSV4KunTdznS9oSZrGLLTs9/9QzjMr1AcXgo3V0SZ/D1Cp4PnWa3B6uqvNDz8bCw1O",
	"z9qOzt2tZ2HT/Q7KctYkdUUo+uj04mievTzNO04yHQnJ/nJeen766uWJ/ijkjFEK3FE8f3mK10Kjuci4",
	"lfH1tzDmmGuQnMRoCnIJEhWAAXaNyG/5k8SD+VORAFwj+pQMoGyoVo/vYm5SrnsE8ScCt2Ed15aah5JB",
	"nl1KrP81CcGzTN56IDSMtmSIZ+TA5x//zyv/I3nlx/+wtJKH6YO9rCyUi2vXDPXx5mHz7wAAAP//1KuH",
	"J7EzAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
